### PR TITLE
Crypto metrics webapp

### PR DESCRIPTION
**Pull request by TracK92**
Create a single-page application that fetches data from a cryptocurrency API and displays it on the page:
- The homepage displays all the data from 100 cryptocurrencies
- The homepage leads to a details page that displays all the details of each cryptocurrency
- Tests are included
- Here is a [video link](https://www.loom.com/share/af98377757be4abb8208a8c6ec332c99) with a preview and description of the project.

NB
I have deployed my project on Netlify. Here is the [LINK](https://papaya-sunburst-a9d343.netlify.app/). However, the issue is that the domain seems unauthorized to access the API. (`Access to XMLHttpRequest at 'https://api.nomics.com/v1/currencies/ticker?key=f4cdb994cd1b7d5758037615a32b7d1b0a7aa743&interval=1d,7d&convert=EUR' from origin 'https://papaya-sunburst-a9d343.netlify.app' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.`). I sincerely cannot begin working afresh on this project due to an issue that is not of my own doing. As you can see from the attached video link, my project is working perfectly. Kindly consider my situation and revert back to me if needed. Thank you.

### CODE REVIEW

**Review by 1GORDON — CHANGES_REQUESTED** [review]
##
## Hi @TracK92 ✋

Good job so far!

## Highlights!
- Followed Gitflow ✔️ 
- Good commit messages ✔️
- Linters are passing ✔️
- Descriptive Pull request ✔️
- Professional readme ✔️

Hello ✋, you have done well reaching this point of the milestone 🤝 . But there are some issues that you still need to work on to go to the next project but you are almost there!

# Status: Required Changes ♻️⛔️

- [ ] Great video presentation 🤝. However, the video didn't highlight a piece of the code you found interesting or you were proud of making.
- [ ] I have noticed the problem with your [live demo link](https://papaya-sunburst-a9d343.netlify.app/). You may opt for another service. You could try Heroku or GitHub Pages to deploy your project again. This is very important for your project to have a Live demo online. If Heroku and Github pages fail to work, I am sure the next reviewer will approve your project since the local version is working properly.

_Check the comments under the review._

## Optional suggestions

- [ ] You could add more tests for your project as specified in the [project requirements](https://github.com/microverseinc/curriculum-react-redux/blob/main/capstone/react_capstone.md). This will make your project fully tested.

_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you consider them as they can improve your code._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread and tag me `@1GORDON` if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by TracK92** [comment]
Hi, 

- So, I have redone the video as per the former reviewer's instructions. Here is the [NEW VIDEO LINK](https://loom.com/share/e9e88fe784034a59a8071898d4377bd4).
- On the issue of deployment, I have also deployed my project using Heroku, gh-pages, and Netlify. The results are the same. The API has denied access on a public domain, which is something I will try to sort out with them or I'll find another API to work with in the foreseeable future. Here are the links for the deployments: 
      - [Netlify](https://papaya-sunburst-a9d343.netlify.app/)
      - [Heroku](https://react-capstone-project1.herokuapp.com/)
      - [Github Pages](https://track92.github.io/crypto-metrics-webapp/)
- Again, as you can see from the video, I have worked really hard on this project and there are no other issues as identified by the first reviewer. Kindly consider approving my project or if possible, provide me with a way to deploy the current project without the API providers' permission. 

Thank you.

**Review by prolajumokeoni — APPROVED** [review]
Hi @TracK92, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 
## Highlights
- No linter errors ✅ 
- Good design 💯 
- Good Pr title and description 💪🏿 

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

- [ ] Make sure that you use correct [Gitflow](https://github.com/microverseinc/curriculum-transversal-skills/blob/main/git-github/articles/gitflow.md) in future projects 👍🏿 

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification @prolajumokeoni.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by TracK92** [comment]
@prolajumokeoni, Thanks a lot.

**Pull request merged**
